name: Vitests

on:
  push:
    branches: [ "main" , "master", "develop" ]
  pull_request:
    branches: [ "main" , "master", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'vscode-extension/package-lock.json'

      - name: Install dependencies
        working-directory: ./vscode-extension
        run: npm ci

      - name: Run tests with coverage
        working-directory: ./vscode-extension
        run: npm run test:coverage
